### PR TITLE
Log error upon missing env vars. Fix #106.

### LINKED ISSUE #106: replace throw with js/console.error when fetching env vars
I think this is where the problem is. Since we are just throwing a Clojurescript exception, the packager is not able to print a nice error from it.

I think that by replacing it by a console.error this would go away since the error would go directly to the console.

line of problem:
- https://github.com/hiposfer/hive/blob/master/src/hive/state.cljs#L27

### PR DESCRIPTION
**Pull request by mehdisadeghi**
@carocad does this change make sense?

### CODE REVIEW

File: src/hive/state.cljs [hunk 1]
```diff
@@ -1,7 +1,8 @@
 (ns hive.state
   (:require [hive.rework.core :as work]
             [hive.rework.util :as tool]
-            [cljs.spec.alpha :as s]))
+            [cljs.spec.alpha :as s]
+            [figwheel.client.utils :as utils]))
```
Comment (carocad) [inline src/hive/state.cljs]: @mehdisadeghi please dont include figwheel into the app itself. 

figwheel is only for code reloading on development, never meant to be included as part of a production app. 

I think you mentioned it but what would be the problem with just using `js/console.error`? I thought about it and to avoid having weird stacktraces I think that we should always return `m` but only print the error if it is not valid.

React native should show the red screen whenever console.error is called, see: https://facebook.github.io/react-native/docs/debugging.html#errors

**Comment by mehdisadeghi** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@carocad/hive?release-channel=bug-iss106-replace-throw

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by mehdisadeghi** [comment]
@carocad yes, I have tested it many times, but it would be nice if you test it too ;)
